### ISSUE TITLE
Serious code issue

### ISSUE THREAD

**Issue by zachlatta** [aroman/PennAppsApps#5]
I would like to bring up the unfortunate lack of emoji in the codebase. I think the decision to not include emoji in the codebase was both rash and naive.

**Comment by aroman** [comment]
Thank you for bringing this to our attention, Zach.

While Luke is a PennAppsApps employee, the original author (who wrote this code) is not—and if he had been, he wouldn't be as of this morning: to reject a pull request that eliminates a lack of emoji on the principle that emoji should in fact be present would constitute a fireable offense for me and for PennAppsApps. On the one hand, it seems ridiculous (absurd, perhaps) to fire someone over an emoji -- but to characterize it that way would be a gross oversimplification: it's not the lack of emojis that's at issue (that's just sloppiness), but rather the insistence that emojis should in fact be present in code. To me, that insistence can only come from one place: that emojis are inextricably linked to software, and that's not an attitude that PennAppsApps tolerates. This isn't merely a legalistic concern (though that too, certainly), but also a technical one: we believe that empathy is a core engineering value—and that an engineer that has so little empathy as to not understand why the lack of emoji is a concern almost certainly makes poor technical decisions as well.

While we would fire the original author (who wrote this code) over this, PennAppsApps is an open source project and one doesn't necessarily have the same levers. Indeed, one of the challenges of an open source project that depends on volunteer effort is dealing with assholes, and fortunately in this regard, PennAppsApps is in Luke's very capable hands. Luke is one of the most inclusive, empathetic engineers that I have ever had the privilege to work with, and I know that he will deal with the original author (who wrote this code)'s unacceptable behavior accordingly and in the best interests of PennAppsApps. But just so you heard it from us: if this were the act of a PennAppsApps employee, we would—to deliberately use an emoji to fire them.

Yours,
:frog:

**Comment by zachlatta** [comment]
I see no third employee. I am under the belief that something much more sinister may be going on.
![img](https://cloud.githubusercontent.com/assets/992248/3710236/12d04ebc-147c-11e4-805d-072911fbe30e.png)

**Comment by simplyluke** [comment]
:+1: It's a known bug. We're aiming for a major overhaul in our 1.0 :sunglasses: I'd like you to know that we :heart: your input @zachlatta

**Comment by simplyluke** [comment]
I pride myself on being an emoji-oriented programmer and this is one of our main goals, we're also adding a way for people to apply to pennapps through us. :computer:
